services:
  miniproxy:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    init: true
    environment:
      CONFIG_FILE: /data/config.mconf
    volumes:
      - ./data:/data:ro
